### ISSUE TITLE
IndexOutOfRangeException: DSP_Mods.CopyInserters/PatchCopyInserters.PlayerAction_BuildSetCopyInfoPostFix

### ISSUE THREAD

**Issue by Chalos-Atiesh** [fezhub/DSP-Mods#9] opened 2021-02-12 17:40 UTC
https://i.imgur.com/oBAoUiY.jpg

Not sure what's relevant so I'll just add everything that may be relevant.

I was on a planet that did not have any inserters laying down a solar panel belt in godmode view. I had copied the previous solar panel and laid ~100 with the copy before this popped up. I was laying them very quickly at a rate of probably 2-3 every second. I saved a the game within a couple minutes and kept the copy. I can upload if needed.

**Comment by sfwr** [comment] 2021-02-12 22:38
Same issue, I'm not sure what the steps to reproduce are.  Seems to happen randomly when I'm building a lot, maybe related to shift-clicking.  I also have this installed, perhaps there's a conflict.

https://dsp.thunderstore.io/package/xiaoye97/AdvancedBuildDestruct/

**Comment by fezhub** [comment] 2021-02-13 02:16
This should be fixed in the 1.1.0 release, was caused by shift-clicking a building plan (unbuilt ghost).
Can you confirm if this is still happening for you in 1.1.0?

**Comment by Chalos-Atiesh** [comment] 2021-02-13 17:27
Ah, that makes sense. I was in god mode and moving the mecha via shift clicking where the previous solar panel was. I can't seem to replicate it reliably. I just updated. Will play for a little bit with it and update.

**Closed as completed** 2021-02-16 13:47 UTC
Labels: bug
